on:
  push:
    branches:
      - main

jobs:
  run_command:
    name: run command
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: run command
        run: |
          echo "inside main job"
  reuse_remote_workflow:
    uses: nickvholbrook/workflow-reuse-remote/.github/workflows/test.yml@main
    with:
      branch: main
  reuse_local_workflow:
    uses: nickvholbrook/workflow-reuse/.github/workflows/test.yml@main
    with:
      branch: main
